# Generated by Django 5.0.1 on 2024-01-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_api_id_alter_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
