# Generated by Django 5.0.1 on 2024-01-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_artist_image'),
        ('songs', '0006_remove_song_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(to='songs.album'),
        ),
        migrations.AddField(
            model_name='artist',
            name='songs',
            field=models.ManyToManyField(to='songs.song'),
        ),
    ]
