# Generated by Django 5.0.1 on 2024-01-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artist_albums_artist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='api_id',
            field=models.CharField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
