# Generated by Django 5.0.1 on 2024-01-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_alter_artist_followers_alter_artist_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='overview',
            field=models.CharField(blank=True, default=''),
        ),
    ]
