# Generated by Django 5.0.1 on 2024-01-07 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('popularity', models.SmallIntegerField()),
                ('preview_url', models.CharField(unique=True)),
                ('album_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs.album')),
                ('artists', models.ManyToManyField(to='artists.artist')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
