# Generated by Django 5.0.1 on 2024-01-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_album_api_id_song_api_id_alter_album_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
