# Generated by Django 5.0.1 on 2024-01-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_song_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='preview_url',
            field=models.URLField(null=True),
        ),
    ]
