# Generated by Django 5.0.1 on 2024-01-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_remove_song_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='api_id',
            field=models.CharField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='api_id',
            field=models.CharField(null=True, unique=True),
        ),
    ]
