# Generated by Django 5.0.1 on 2024-01-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_alter_album_api_id_alter_song_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
