# Generated by Django 5.0.1 on 2024-01-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_alter_album_release_date_alter_album_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(null=True),
        ),
    ]
