# Generated by Django 5.0.1 on 2024-01-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_alter_album_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(),
        ),
    ]
