# Generated by Django 5.0.1 on 2024-01-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_alter_song_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
